const sessionsList = [
    {
      id: '1',
      day: '18',
      month: 'Mar',
      name: 'Eric Froiland',
      session: 'Executive coaching',
      time: '10:00 AM',
      image: 'https://via.placeholder.com/50',
    },
    {
      id: '2',
      day: '20',
      month: 'Mar',
      name: 'Sarah Jones',
      session: 'Career counseling',
      time: '01:00 AM',
      image: 'https://via.placeholder.com/50',
    },
    {
        id: '3',
        day: '05',
        month: 'Mar',
        name: 'Sarah KK',
        session: 'Career counseling',
        time: '11:00 AM',
        image: 'https://via.placeholder.com/50',
      },
      {
        id: '4',
        day: '25',
        month: 'Mar',
        name: 'Motos Jones',
        session: 'Career counseling',
        time: '03:00 AM',
        image: 'https://via.placeholder.com/50',
      },
      {
        id: '5',
        day: '25',
        month: 'Mar',
        name: 'Candle Jones',
        session: 'Career counseling',
        time: '03:00 AM',
        image: 'https://via.placeholder.com/50',
      },
      {
        id: '6',
        day: '25',
        month: 'Mar',
        name: 'KK Bhaskar',
        session: 'Career counseling',
        time: '03:00 AM',
        image: 'https://via.placeholder.com/50',
      },
      {
        id: '7',
        day: '25',
        month: 'Mar',
        name: 'Jones mall',
        session: 'Career counseling',
        time: '03:00 AM',
        image: 'https://via.placeholder.com/50',
      },
      {
        id: '8',
        day: '25',
        month: 'Mar',
        name: 'Krish Hama',
        session: 'Career counseling',
        time: '03:00 AM',
        image: 'https://via.placeholder.com/50',
      },

    // Add more session objects as needed
  ];
  export default sessionsList;